create table if not exists site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists workspace_items (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  body text not null default '',
  item_date text not null default '',
  image_url text not null default '',
  pinned boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists photos (
  id bigint generated by default as identity primary key,
  scope text not null,
  title text not null default '',
  caption text not null default '',
  url text not null,
  object_key text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists love_events (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  event_date text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists love_wishes (
  id bigint generated by default as identity primary key,
  title text not null,
  note text not null default '',
  completed boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists quarter_goals (
  id bigint generated by default as identity primary key,
  quarter text not null,
  title text not null,
  note text not null default '',
  progress integer not null default 0,
  status text not null default '进行中',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists travel_plans (
  id bigint generated by default as identity primary key,
  destination text not null,
  time_range text not null default '',
  note text not null default '',
  status text not null default '计划中',
  image_url text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('site-media', 'site-media', true)
on conflict (id) do update set public = excluded.public;
